import {LiveClient,finite,show,lapTime,leaves,pathFor,nearest,displayTrace,gearLabel} from './live.js';
const app=document.querySelector('#app');
const ui={tab:'summary',cursor:0,compare:false};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>finite(value)?new Date(value*1000).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Date unavailable';
const clock=value=>finite(value)?new Date(value*1000).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}):'Time unavailable';
const client=new LiveClient(()=>render());
window.addEventListener('pagehide',()=>client.stop());
const stintNumber=id=>{const stints=client.state.overview?.recording.stints||[];return stints.find(item=>item.id===id)?.number+1||id;};
const lapLabel=lap=>`Lap ${lap.number??'?'} · Stint ${stintNumber(lap.stint_id)} · ${lap.status}`;
const option=(id,label,selected)=>`<option value="${esc(id)}" ${String(id)===String(selected)?'selected':''}>${esc(label)}</option>`;
const empty=(title,body)=>`<section class="panel empty-panel"><h2>${esc(title)}</h2><p>${esc(body)}</p></section>`;
const metric=(label,value,note)=>`<article class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></article>`;
function picker(id,label,items,selected){
 const name=items.find(item=>item.id===selected)?.name||`All ${label.toLowerCase()}s`;
 return `<label class="picker"><span class="eyebrow">${label}</span><select id="${id}" aria-label="${label}">${option('all',`All ${label.toLowerCase()}s`,selected)}${items.map(item=>option(item.id,item.name,selected)).join('')}</select><span class="selection-name">${esc(name)}</span></label>`;
}
function sidebar(){
 const s=client.state,tracks=[...new Map(s.library.map(r=>[r.track.id,r.track])).values()];
 const cars=[...new Map(s.library.filter(r=>s.trackId==='all'||r.track.id===s.trackId).map(r=>[r.car.id,r.car])).values()];
 return `<aside class="sidebar"><a class="brand" href="#main"><span class="brand-mark">A</span><span>APEX<small>SESSION STUDIO</small></span></a><div class="library-label">Session library</div><div class="filters"><label class="picker"><span class="eyebrow">DATE</span><input id="recording-date" type="date" aria-label="Recording date" value="${s.date}"></label>${picker('track-select','Circuit',tracks,s.trackId)}${picker('car-select','Car',cars,s.carId)}</div><div class="sidebar-heading"><span>RECORDINGS</span><span>${client.visible().length}</span></div><div class="session-list">${client.visible().map(r=>`<button class="session-card ${r.id===s.recordingId?'selected':''}" data-recording="${esc(r.id)}" aria-pressed="${r.id===s.recordingId}"><span class="session-date">${esc(date(r.started_at))}<span>${esc(clock(r.started_at))}</span></span><strong>${esc(r.track.name)}</strong><span class="session-car">${esc(r.car.name)}</span><span class="session-bottom">${esc(r.status)}</span></button>`).join('')||'<p class="sidebar-empty">No recordings for this date and selection.</p>'}</div>${s.hasMore?'<button class="text-button" id="load-older">Load more from this date</button>':''}<div class="sidebar-bottom"><div class="storage-status"><span>Local database<small>${s.error?'Connection interrupted':s.loading?'Loading…':'Refresh page to update'}</small></span><span class="status-dot ${s.error?'offline':''}"></span></div></div></aside>`;
}
function pace(o){
 const laps=o.laps.filter(lap=>lap.eligible);
 if(!laps.length)return empty('No clean complete laps','Best and average times require a fully observed lap with known incident data, no incidents, pit visit or telemetry gap.');
 const min=Math.min(...laps.map(l=>l.seconds))-.25,max=Math.max(...laps.map(l=>l.seconds))+.25;
 const x=i=>55+i/Math.max(1,laps.length-1)*645,y=v=>170-(v-min)/(max-min)*140;
 return `<section class="panel pace-panel"><div class="panel-heading"><h2>Clean lap pace</h2></div><svg class="pace-chart" viewBox="0 0 750 225" role="img" aria-label="Clean lap times">${[0,.5,1].map(f=>`<text x="0" y="${y(min+f*(max-min))+4}" class="axis-label">${lapTime(min+f*(max-min))}</text>`).join('')}<polyline points="${laps.map((l,i)=>`${x(i)},${y(l.seconds)}`).join(' ')}" fill="none" stroke="var(--accent)" stroke-width="2"/>${laps.map((l,i)=>`<circle cx="${x(i)}" cy="${y(l.seconds)}" r="4" fill="var(--accent)"><title>${esc(lapLabel(l))}: ${lapTime(l.seconds)}</title></circle>`).join('')}</svg></section>`;
}
function sectors(o){
 if(!o.sectors?.length)return empty('Sector data unavailable','This recording has no SDK sector boundaries.');
 return `<section class="panel sector-panel"><div class="panel-heading"><div><h2>Sector pace</h2><p>Estimated times · Clean laps only</p></div></div><div class="table-scroll"><table><thead><tr><th>Sector</th><th>Best</th><th>Average</th><th>Laps</th></tr></thead><tbody>${o.sectors.map(s=>`<tr><td>Sector ${s.number}</td><td class="mono">${lapTime(s.best)}</td><td class="mono">${lapTime(s.average)}</td><td>${s.count}</td></tr>`).join('')}</tbody></table></div><p class="panel-copy">${o.sectors.length} sectors from this track’s SDK metadata. Times estimate the boundary crossing between adjacent telemetry samples.</p></section>`;
}
function conditions(o){
 return `<section class="panel conditions-panel review-conditions"><div class="panel-heading"><h2>Recorded conditions</h2></div><dl>${[['Circuit length',o.track.length_km,'km'],['Air temperature',o.latest?.air_temp,'°C'],['Track temperature',o.latest?.track_temp,'°C'],['Wind',finite(o.latest?.wind)?o.latest.wind*3.6:null,'km/h']].map(([label,value,unit])=>`<div><dt>${label}</dt><dd>${show(value)} ${unit}</dd></div>`).join('')}</dl></section>`;
}
function summary(o){
 return `<div class="metric-grid">${metric('Best clean lap',lapTime(o.best?.seconds),o.best?esc(lapLabel(o.best)):'No clean complete laps')}${metric('Average clean lap',lapTime(o.average),finite(o.deviation)?`± ${show(o.deviation,3)}s standard deviation`:'Clean complete laps only')}${metric('Clean complete laps',o.eligible_count,`${o.laps.length} observed lap segments`)}</div><div class="summary-grid">${pace(o)}${sectors(o)}</div>${conditions(o)}<section class="panel lap-panel"><div class="panel-heading"><h2>Lap history</h2></div><div class="table-scroll"><table><thead><tr><th>Lap / stint</th><th>Time</th><th>Δ best</th><th>Coverage</th><th></th></tr></thead><tbody>${o.laps.map(l=>`<tr class="${l.id===o.best?.id?'best-row':''}"><td>${l.number??'?'} / ${stintNumber(l.stint_id)}</td><td class="mono">${lapTime(l.seconds)}</td><td class="mono">${l.eligible&&o.best?'+'+show(l.seconds-o.best.seconds,3):'—'}</td><td><span class="lap-status ${l.eligible?'clean':'other'}">${esc(l.status)}</span><small class="validity-note">${esc(l.validity)}</small></td><td><button class="small-select" data-lap="${l.id}">Analyze</button></td></tr>`).join('')||'<tr><td colspan="5">No laps recorded.</td></tr>'}</tbody></table></div></section>`;
}
function lapPicker(side,label,o){
 const s=client.state,key=side==='selected'?'lapId':'referenceId',laps=client.laps(side);
 const stints=o.recording.stints.filter(stint=>o.laps.some(l=>l.stint_id===stint.id));
 return `<fieldset class="lap-filters"><legend>${label}</legend><div class="lap-filter-row"><label>Stint<select id="${side}-stint" aria-label="${label} stint">${option('all','All stints',s[side+'Stint'])}${stints.map(stint=>option(stint.id,`Stint ${stintNumber(stint.id)}`,s[side+'Stint'])).join('')}</select></label><label>Lap condition<select id="${side}-condition" aria-label="${label} condition">${[['all','All conditions'],['clean','Clean'],['incident','Incident'],['partial','Partial / unfinished'],['gap','Data gap'],['pit','Pit / garage'],['unknown','Incident data unknown']].map(([id,name])=>option(id,name,s[side+'Condition'])).join('')}</select></label></div><label class="lap-picker">Lap<select id="${side}-lap" aria-label="${label}" ${laps.length?'':'disabled'}>${laps.length?laps.map(l=>option(l.id,`${lapLabel(l)} · ${lapTime(l.seconds)}`,s[key])).join(''):'<option>No matching laps</option>'}</select></label></fieldset>`;
}
function chart(a,b,key,label,unit,max,min=0){
 const {rangeStart:start,rangeEnd:end}=client.state;
 return `<div class="trace-block"><div class="trace-heading"><h3>${label}<span>${unit}</span></h3><div class="trace-values"><span class="accent" data-live="${key}">—</span><span class="purple" data-reference="${key}">—</span></div></div><svg class="trace-chart" data-trace="${key}" viewBox="0 0 920 136" role="img" aria-label="Recorded ${label.toLowerCase()} by lap distance">${[0,.5,1].map(f=>`<line x1="54" x2="896" y1="${111-f*94}" y2="${111-f*94}" class="chart-grid"/><text x="8" y="${115-f*94}" class="axis-label">${Math.round(min+(max-min)*f)}</text>`).join('')}${[0,.25,.5,.75,1].map(f=>`<text x="${54+f*842}" y="132" text-anchor="middle" class="axis-label">${show((start+f*(end-start))*100)}%</text>`).join('')}<path d="${pathFor(b,key,max,min,start,end)}" fill="none" stroke="var(--purple)" stroke-width="2" stroke-dasharray="5 3"/><path d="${pathFor(a,key,max,min,start,end)}" fill="none" stroke="var(--accent)" stroke-width="2"/><line class="crosshair" y1="17" y2="111" stroke="var(--text)" stroke-opacity=".4" stroke-dasharray="3 4"/></svg></div>`;
}
function analytics(o){
 if(!o.laps.length)return empty('No telemetry yet','Record a stint, then refresh this page.');
 const s=client.state,a=displayTrace(s.traces.selected),b=displayTrace(s.traces.reference);
 const selected=o.laps.find(l=>l.id===s.lapId),reference=o.laps.find(l=>l.id===s.referenceId);
 const gap=selected?.eligible&&reference?.eligible?selected.seconds-reference.seconds:null;
 const speed=Math.max(100,...[...a,...b].map(p=>p.speed||0)),angle=Math.max(45,...[...a,...b].map(p=>Math.abs(p.steering||0)));
 return `<div class="comparison-toolbar">${lapPicker('selected','Selected lap',o)}${lapPicker('reference','Reference lap',o)}</div><div class="focus-toolbar"><label>Focus<select id="sector-focus" aria-label="Chart focus">${option('all','Full lap',s.focus)}${(o.sectors||[]).map(sector=>option(sector.number,`Sector ${sector.number}`,s.focus)).join('')}${option('custom','Custom distance range',s.focus)}</select></label>${s.focus==='custom'?`<label>From (%)<input id="range-start" type="number" min="0" max="99.9" step="0.1" value="${show(s.rangeStart*100,1)}"></label><label>To (%)<input id="range-end" type="number" min="0.1" max="100" step="0.1" value="${show(s.rangeEnd*100,1)}"></label><button id="apply-range" class="small-select">Apply range</button>`:''}<span id="range-message">Use a custom range to inspect a corner. Named corner boundaries are unavailable.</span></div><div class="analytics-grid"><section class="panel telemetry-panel"><div class="panel-heading"><div><h2>Lap comparison</h2><p>${show(s.rangeStart*100)}–${show(s.rangeEnd*100)}% of lap distance</p></div><div class="trace-legend"><span><i></i> Selected</span><span><i></i> Reference</span></div></div>${!selected||!reference?'<p class="panel-copy">Choose filters with matching laps to compare both traces.</p>':''}<div class="telemetry-stack">${chart(a,b,'speed','Speed','km/h',speed)}${chart(a,b,'throttle','Throttle','%',100)}${chart(a,b,'brake','Brake','%',100)}${chart(a,b,'steering','Steering angle','°',angle,-angle)}</div><div class="distance-control"><div><label for="distance-cursor">Inspect distance</label><output id="distance-value"></output></div><input type="range" id="distance-cursor" min="0" max="1000" aria-label="Inspect lap distance"><div class="cursor-gears"><span class="accent">Selected gear <strong id="selected-gear">—</strong></span><span class="purple">Reference gear <strong id="reference-gear">—</strong></span></div></div><div class="panel-footnote">Gaps remain visible. Zooming loads telemetry within the selected range. Steering is in degrees; cursor values use nearby recorded samples.</div></section><div class="analytics-side"><section class="panel lap-detail"><div class="panel-heading"><h2>Lap times</h2></div><dl><div><dt>Selected</dt><dd>${lapTime(selected?.seconds)}</dd></div><div><dt>Reference</dt><dd>${lapTime(reference?.seconds)}</dd></div><div><dt>Difference</dt><dd>${finite(gap)?`${gap>=0?'+':''}${show(gap,3)}s`:'—'}</dd></div><div><dt>Selected coverage</dt><dd>${esc(selected?.status||'No matching lap')}</dd></div><div><dt>Reference coverage</dt><dd>${esc(reference?.status||'No matching lap')}</dd></div></dl><p class="panel-copy">Time differences are shown for clean, complete laps.</p></section></div></div>`;
}
function setup(o){
 const s=client.state,index=s.snapshots.findIndex(item=>item.id===s.snapshotId),snapshot=s.snapshots[index];
 if(!snapshot)return empty('No setup recorded','A setup is captured once when a stint begins.');
 const previous=s.snapshots[index-1],compare=ui.compare&&!!previous;
 const before=new Map(leaves(previous?.setup).map(item=>[item.path,item.value]));
 const rows=(value,prefix=[])=>leaves(value,prefix).map(item=>{const changed=compare&&before.get(item.path)!==item.value;return `<div class="setup-row ${changed?'changed':''}"><dt>${esc(item.path)}</dt><dd>${changed?`<del>${esc(before.get(item.path)??'Not present')}</del>`:''}<span>${esc(item.value)}</span></dd></div>`;}).join('');
 const current=new Set(leaves(snapshot.setup).map(item=>item.path)),removed=compare?leaves(previous.setup).filter(item=>!current.has(item.path)):[];
 const groups=snapshot.setup&&typeof snapshot.setup==='object'?Object.entries(snapshot.setup):[];
 return `<div class="setup-toolbar"><label><span class="eyebrow">STINT</span><select id="setup-snapshot" aria-label="Setup stint">${s.snapshots.map(item=>option(item.id,`Stint ${stintNumber(item.stint_id)} · ${clock(item.captured_at)} · Starting setup`,s.snapshotId)).join('')}</select></label><label class="compare-toggle"><input id="compare-setup" type="checkbox" ${compare?'checked':''} ${previous?'':'disabled'}>Compare previous stint</label></div><div class="setup-overview"><div><h2>${esc(o.car.name)}</h2><p>${esc(date(snapshot.captured_at))} · Stint ${stintNumber(snapshot.stint_id)}</p></div><span class="snapshot-badge">Setup at stint start</span></div>${snapshot.parse_error?'<div class="notice">Some setup data could not be parsed.</div>':''}${snapshot.setup==null?empty('Setup unavailable','The SDK did not expose a setup at the start of this stint.'):`<div class="setup-sections">${groups.length?groups.map(([name,value])=>`<section class="panel setup-card"><div class="panel-heading"><h2>${esc(name)}</h2></div><dl>${rows(value,[name])}</dl></section>`).join(''):`<section class="panel setup-card"><dl>${rows(snapshot.setup)}</dl></section>`}</div>`}${removed.length?`<section class="panel setup-card"><div class="panel-heading"><h2>No longer present</h2></div><dl>${removed.map(item=>`<div class="setup-row"><dt>${esc(item.path)}</dt><dd><del>${esc(item.value)}</del></dd></div>`).join('')}</dl></section>`:''}<p class="panel-copy">One starting setup per stint. Historical recordings use the earliest stored snapshot for each stint. Values and units follow the recorded car setup.</p>`;
}
function render(){
 const s=client.state,o=s.overview,scroll=document.querySelector('.sidebar')?.scrollTop;
 app.innerHTML=`${sidebar()}<main id="main" tabindex="-1"><header class="topbar"><div class="breadcrumb">WORKSPACE <span>Session review</span></div><span class="demo-badge ${s.error?'error-badge':''}">${s.error?'CONNECTION INTERRUPTED':s.loading?'LOADING':'SESSION REVIEW'}</span></header><div class="main-content">${s.error?`<div class="notice" role="status">${esc(s.error)}<button id="retry" class="small-select">Retry</button></div>`:''}${o?`<div class="session-header"><div><div class="eyebrow">${esc(date(o.recording.started_at))} · ${esc(clock(o.recording.started_at))} · ${esc(o.recording.status)}</div><h1>${esc(o.track.name)} <span class="layout-tag">${esc(o.track.layout)}</span></h1><div class="car-subtitle">${esc(o.car.name)} / ${esc(o.track.country)}</div></div></div><div class="tabbar"><div role="tablist" aria-label="Session views">${['summary','analytics','setup'].map(tab=>`<button class="tab ${ui.tab===tab?'active':''}" id="tab-${tab}" data-tab="${tab}" role="tab" aria-controls="session-panel" aria-selected="${ui.tab===tab}" tabindex="${ui.tab===tab?0:-1}">${tab[0].toUpperCase()+tab.slice(1)}</button>`).join('')}</div><span class="preview-label">Recorded data · On demand</span></div><div id="session-panel" role="tabpanel" aria-labelledby="tab-${ui.tab}">${ui.tab==='summary'?summary(o):ui.tab==='analytics'?analytics(o):setup(o)}</div>`:empty(s.loading?'Loading recordings…':s.error?'Viewer unavailable':'No recordings for this date',s.loading?'Reading your local session library.':s.error?'Check the viewer terminal, then retry.':'Choose another date, or record a stint and refresh this page.')}<footer class="main-footer"><span>APEX / SESSION STUDIO</span><span>After-session analysis</span></footer></div></main>`;
 bind();if(scroll!==undefined)document.querySelector('.sidebar').scrollTop=scroll;
}
function bind(){
 document.querySelector('#recording-date').onchange=e=>{if(e.target.value)client.selectFilter('date',e.target.value);};
 document.querySelector('#track-select').onchange=e=>client.selectFilter('trackId',e.target.value);
 document.querySelector('#car-select').onchange=e=>client.selectFilter('carId',e.target.value);
 document.querySelectorAll('[data-recording]').forEach(b=>b.onclick=()=>client.selectRecording(b.dataset.recording));
 document.querySelector('#load-older')?.addEventListener('click',()=>{client.state.libraryLimit+=100;client.refresh();});
 document.querySelector('#retry')?.addEventListener('click',()=>client.refresh());
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{ui.tab=b.dataset.tab;render();document.querySelector(`#tab-${ui.tab}`).focus();});
 document.querySelector('[role=tablist]')?.addEventListener('keydown',e=>{const tabs=['summary','analytics','setup'];let i=tabs.indexOf(ui.tab);if(e.key==='ArrowRight')i=(i+1)%3;else if(e.key==='ArrowLeft')i=(i+2)%3;else if(e.key==='Home')i=0;else if(e.key==='End')i=2;else return;e.preventDefault();ui.tab=tabs[i];render();document.querySelector(`#tab-${ui.tab}`).focus();});
 document.querySelectorAll('[data-lap]').forEach(b=>b.onclick=()=>{client.state.lapId=b.dataset.lap;client.state.selectedStint='all';client.state.selectedCondition='all';ui.tab='analytics';client.refresh(false);});
 for(const [id,key] of [['selected-lap','lapId'],['reference-lap','referenceId']])document.getElementById(id)?.addEventListener('change',e=>{client.state[key]=e.target.value;client.refresh(false);});
 for(const side of ['selected','reference'])for(const [suffix,key] of [['stint','Stint'],['condition','Condition']])document.querySelector(`#${side}-${suffix}`)?.addEventListener('change',e=>{client.state[side+key]=e.target.value;client.refresh(false);});
 document.querySelector('#sector-focus')?.addEventListener('change',e=>{const s=client.state;s.focus=e.target.value;if(s.focus==='custom'){render();return;}const sector=s.overview.sectors?.find(item=>String(item.number)===s.focus);s.rangeStart=sector?.start??0;s.rangeEnd=sector?.end??1;ui.cursor=s.rangeStart;client.refresh(false);});
 document.querySelector('#apply-range')?.addEventListener('click',()=>{const start=Number(document.querySelector('#range-start').value)/100,end=Number(document.querySelector('#range-end').value)/100;if(!(0<=start&&start<end&&end<=1)){document.querySelector('#range-message').textContent='Choose a start below the end, between 0% and 100%.';return;}client.state.rangeStart=start;client.state.rangeEnd=end;ui.cursor=start;client.refresh(false);});
 document.querySelector('#setup-snapshot')?.addEventListener('change',e=>{client.state.snapshotId=Number(e.target.value);render();});
 document.querySelector('#compare-setup')?.addEventListener('change',e=>{ui.compare=e.target.checked;render();});
 if(ui.tab==='analytics'&&document.querySelector('#distance-cursor')){
  const a=displayTrace(client.state.traces.selected),b=displayTrace(client.state.traces.reference),{rangeStart:start,rangeEnd:end}=client.state;
  const inspect=x=>{ui.cursor=Math.max(start,Math.min(end,x));const selected=nearest(a,ui.cursor),reference=nearest(b,ui.cursor),fraction=(ui.cursor-start)/(end-start);
   document.querySelector('#distance-value').textContent=`${show(ui.cursor*100)}%`;
   document.querySelector('#distance-cursor').value=Math.round(fraction*1000);
   for(const key of ['speed','throttle','brake','steering']){document.querySelector(`[data-live="${key}"]`).textContent=show(selected?.[key]);document.querySelector(`[data-reference="${key}"]`).textContent=show(reference?.[key]);}
   document.querySelector('#selected-gear').textContent=gearLabel(selected?.gear);document.querySelector('#reference-gear').textContent=gearLabel(reference?.gear);
   document.querySelectorAll('.crosshair').forEach(line=>{line.setAttribute('x1',54+fraction*842);line.setAttribute('x2',54+fraction*842);});
  };
  document.querySelector('#distance-cursor').oninput=e=>inspect(start+Number(e.target.value)/1000*(end-start));
  document.querySelectorAll('[data-trace]').forEach(svg=>svg.onpointermove=e=>{const r=svg.getBoundingClientRect();inspect(start+((e.clientX-r.left)/r.width*920-54)/842*(end-start));});inspect(ui.cursor);
 }
}
render();client.refresh();
